### PR TITLE
Mutation input and output fields should support thunks

### PR DESCRIPTION
**Pull request by skevy**

### CODE REVIEW

**Comment by wincent** [comment]
Thanks! I think it's probably worth updating the test cases to exercise this functionality. What do you think?

**Comment by skevy** [comment]
Just realized this relates to #22...

How does an array work in this case (as opposed to an object or a thunk)? What's the purpose?

cc @dschafer

**Comment by dschafer** [comment]
> How does an array work in this case (as opposed to an object or a thunk)? What's the purpose?

I meant thunk or object. Too much time in PHP!

**Comment by skevy** [comment]
@dschafer ha. Ok. Well then this should do it then :)

**Comment by wincent** [comment]
Sorry for letting this sit here and go stale, @skevy. Would you be able do rebase so that I can merge this in cleanly?

**Comment by skevy** [comment]
Very sorry I let this sit! LGTM :)

**Comment by skevy** [comment]
Any update on this @wincent @kassens @dschafer ?

**Comment by dschafer** [comment]
Sorry for the delay!

**Pull request merged**
