### PR TITLE
add support graphql ^0.11.0

### PR DESCRIPTION
**Pull request by HsuTing**
Like the title, just add to `graphql` version `^0.11.0`.

### CODE REVIEW

**Comment by kassens** [comment]
Thanks for doing this, could you complete the only form for the CLA?

**Comment by kassens** [comment]
Thanks, now we just have to cut a release

**Comment by j0k3r** [comment]
@kassens @wincent any chance to make a new release with support of graphql ^0.11.0?

**Comment by kassens** [comment]
Just published `graphql-relay@0.5.3` with the updated dependency. Sorry for the delay here!

**Pull request merged**
