### PR TITLE
Improve mutationWithClientId types with generics

### PR DESCRIPTION
**Pull request by noghartt**

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
good

**Review by fersilva16 — APPROVED** [review]

**Review by saihaj — APPROVED** [review]

**Comment by saihaj** [comment]
@IvanGoncharov can we land this?

**Review by vit0rr — APPROVED** [review]
Nice one

**Comment by noghartt** [comment]
I would like to type `inputFields` and `outputFields` too, but I couldn't find a better way than put something like:

```ts
  inputFields: Record<keyof TInput, (() => GraphQLInputFieldConfig) | GraphQLInputFieldConfig>;
  outputFields: Record<keyof TOutput, (() => GraphQLFieldConfig<TOutput, TContext>) | GraphQLFieldConfig<TOutput, TContext>>;
```

In this case, we override `ThunkObjMap` util type. Would have a better way to do it?

**Comment by benjie** [comment]
@graphql/tsc I don't think this project explicitly has a maintainer right now?

**Comment by benjie** [comment]
@graphql/tsc I don't think this project explicitly has a maintainer right now, and other than @andimarek merging a link fix recently hasn't had any updates since 2021. It looks like the overhead of maintaining it should be relatively minor, but in the mean time I move that we merge and ship this PR. I have no experience with this library, but the changes are small and they appear to be non-breaking since all the generics added have defaults. Does anyone have any concerns about this? I'm going to leave it a month (since it's already been over a year) for feedback, and if there's no concerns raised I'll go ahead and merge it after then.

**Review by robrichard — APPROVED** [review]

**Review by enisdenjo — APPROVED** [review]

**Review by benjie — APPROVED** [review]

**Pull request merged**
