### PR TITLE
Add CHANGELOG.md

### LINKED ISSUE #34: Add CHANGELOG
I just noticed while preparing the v0.3.3 release that we don't have an actual changelog, so I had to link people to: https://github.com/graphql/graphql-relay-js/compare/v0.3.2...v0.3.3

Let's add one, so we can have something more human-readable, albeit at a slight maintenance cost.

### PR DESCRIPTION
**Pull request by wincent**
Fixes #34.

### CODE REVIEW

**Comment by dschafer** [comment]
We'd been using https://github.com/graphql/graphql-relay-js/releases in the past for this (so you could add the info on 0.3.3 there and then link to https://github.com/graphql/graphql-relay-js/releases/tag/v0.3.3)

**Comment by dschafer** [comment]
Just added the info from this PR into https://github.com/graphql/graphql-relay-js/releases/tag/v0.3.3

**Comment by wincent** [comment]
Ah cool. Makes sense to only have it in one place. Let me resubmit this as a link to the releases page.

**Comment by dschafer** [comment]
> Let me resubmit this as a link to the releases page.

Perfect!

**Pull request merged**
