### PR TITLE
chore: Update for graphql-js v15.x

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
cc @kassens – if you have a moment to pull this in, so we can get the right peer dependency

**Comment by TrySound** [comment]
Friendly ping @kassens

**Comment by glen-84** [comment]
Closes #245.

**Comment by anchan828** [comment]
any updates? graphql-relay needs to support graphql v15.x
I got npm v7 error: `ERESOLVE unable to resolve dependency tree`

```
# npm resolution error report

2020-10-23T01:20:43.965Z

While resolving: my-app@1.0.0
Found: graphql@15.3.0
node_modules/graphql
  graphql@"15.3.0" from the root project

Could not resolve dependency:
peer graphql@"^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-relay@0.6.0
node_modules/graphql-relay
  graphql-relay@"0.6.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "graphql",
    "version": "15.3.0",
    "whileInstalling": {
      "name": "my-app",
      "version": "1.0.0",
      "path": "/home/anchan828/repos/my-app"
    },
    "location": "node_modules/graphql",
    "dependents": [
      {
        "type": "prod",
        "name": "graphql",
        "spec": "15.3.0",
        "from": {
          "location": "/home/anchan828/repos/my-app"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "graphql",
    "spec": "^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0",
    "error": "INVALID",
    "from": {
      "name": "graphql-relay",
      "version": "0.6.0",
      "whileInstalling": {
        "name": "my-app",
        "version": "1.0.0",
        "path": "/home/anchan828/repos/my-app"
      },
      "location": "node_modules/graphql-relay",
      "dependents": [
        {
          "type": "prod",
          "name": "graphql-relay",
          "spec": "0.6.0",
          "from": {
            "location": "/home/anchan828/repos/my-app"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**Comment by glen-84** [comment]
@IvanGoncharov Is this project still maintained?

**Comment by IvanGoncharov** [comment]
@glen-84 Yes, it is.
Sorry for the delay.
I Will work on a new release.
The long term plan is to merge this functionality into `graphql-js` to simplify maintenance.

**Comment by glen-84** [comment]
@IvanGoncharov Friendly ping.

**Comment by taion** [comment]
No reason to keep this PR open any more, anyway, given that https://github.com/graphql/graphql-relay-js/pull/266 was merged.

**Pull request closed without merging**
