### PR TITLE
Add totalCount field

### PR DESCRIPTION
**Pull request by saeedghx68**
Based on [this link(Pagination)](http://graphql.org/learn/pagination/), I needed to have something like `total count` or similar. But, unfortunately the official `graphql-relay-js` library doesn't provide me this feature. 

While I think others might benefit from this feature, I decided to implement it by myself and send a pull request.

For example:
```
{
  viewer{
    boProviderList(before:"YXJyYXljb25uZWN0aW9uOjc="){
      totalCount
      edges{
        node {
          id
          username
        }
        cursor
      }
    }
  }
}
```
Result:

```
{
  "data": {
    "viewer": {
      "boProviderList": {
        "totalCount": 7,
        "edges": [
          {
            "node": {
              "id": "UHJvdmlkZXI6NTlhYTcxMGQyZTRmZDEzMWU4Yzg5ZGM2",
              ...
```
As you can see, we have `totalCount` field now.
Please let me know if any change is needed. Thank you

### CODE REVIEW

**Comment by saeedghx68** [comment]
@wincent please check out my pull request
I think it's necessary for pagination and I'm waiting for your response.
tnx alot.

**Comment by jaydenseric** [comment]
I really need this; can it be merged?

**Comment by jaydenseric** [comment]
Actually, see this comment on a duplicate PR: https://github.com/graphql/graphql-relay-js/pull/109#issuecomment-267734541

**Comment by Svehla** [comment]
Btw you can hack it with
- rewriting connectionFromArray to custom connectionFromArray -> it have to return totalCount
- update connecionDefinition with this code

```
type: connectionDefinitions({
  name: 'ChatMessages',
  nodeType: ChatMessageType,
  connectionFields: {
    totalCount: { type: new GraphQLNonNull(GraphQLInt) }
  }
}).connectionType,
```
It'll add totalCount to your connection type
in code:
https://github.com/graphql/graphql-relay-js/blob/4fdadd3bbf3d5aaf66f1799be3e4eb010c115a4a/src/connection/connection.js#L89

**Comment by mxmlnglt** [comment]
Should be closed, as per comment: https://github.com/graphql/graphql-relay-js/pull/109#issuecomment-302916585

**Comment by IvanGoncharov** [comment]
Sorry for the long delay 🙇 
Closing this issue based on the links pointed by @mxmlnglt in above comment.

**Pull request closed without merging**
