### PR TITLE
chore(dependencies): use prettier as a dev dependency

### PR DESCRIPTION
**Pull request by JeandeCampredon**
This is actually breaking my test CI and probably not only mine.

I am not really sure how it ended up there since @kassens' [PR](https://github.com/graphql/graphql-relay-js/pull/222) was adding correctly.
Hope I haven't missed anything important but the test are passing 😄 

would you consider patching the npm version ?

### CODE REVIEW

**Comment by kassens** [comment]
Looks like I messed up in 84ed0008ee17ae439ce67d820a29d1f258addff8. Thanks for fixing!

**Comment by petrbela** [comment]
Could this be packaged into a new release please? :)

**Comment by TrySound** [comment]
Hi @kassens. Is it possible to cut a release with this fix? It requires me to add yarn resolutions otherwise yarn use wrong version in node_modules/.bin.

**Comment by cliedeman** [comment]
Bump for a fix too please. The resolutions seem to be buggy and when adding a new dep reverts to prettier 1 :(.

**Comment by TrySound** [comment]
@cliedeman I always run `yarn` after installing or removing deps to solve this.

**Comment by cliedeman** [comment]
@TrySound thanks. That definitetly fixes it. Its just confusing and easy to forget. It only seems to happen in conjuction with yarn workspaces

**Comment by TrySound** [comment]
Friendly ping @kassens

**Comment by trmaphi** [comment]
Would we provide a patch version on this change? My Lambda function is using this package and the `prettier` included built package at runtime is quite heavy.

**Comment by papandreou** [comment]
@IvanGoncharov, maybe you can help get a new version published with this change? 🙇

**Pull request merged**
