### PR TITLE
Switch to custom base64 implementation

### LINKED ISSUE #152: toGlobalId/fromGlobalId not working inside React Native
I tried using this library's `toGlobalId` and `fromGlobalId` from a React Native application, however I got an error that `Buffer` is not defined (it's used in [src/utils/base64.js](https://github.com/graphql/graphql-relay-js/blob/9496e3ff2caa5919cda175c8fddbfac743954727/src/utils/base64.js)). It seems that `Buffer` is only available from NodeJS...

If you consider that this library should also be available from React Native (or a browser), at least some changes need to be made to base64.js.

In the time being I'll probably just use join/split.

By the way, the reason I was trying to use this library from React Native is to do something similar to http://graphql.org/blog/rest-api-graphql-wrapper/.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Previously we used Node's API for converting to/from base64
but it limits portability of this library to defirent enviroments
include Deno

Fixes #152

### CODE REVIEW

**Comment by itajaja** [comment]
hi! how's this a breaking change? is it safe to upgrade, and if not, why?

**Comment by itajaja** [comment]
I tried to upgrade to 0.8.0 and my tests fail with some `Invalid code point` errors, which probably derive from this change. is it a bug? or should i take care of the breaking change on my side? in general I don't see how change implementation for b64 should be a breaking change. any reason as to not use an existing impl, eg https://www.npmjs.com/package/base-64 ?

**Comment by IvanGoncharov** [comment]
@itajaja It shouldn't be any observable changes for valid IDs, meaning your client treats them as opaque strings.
However, I simplify our own base64 implementation and now it rejects a bunch of invalid codes.
Without additional details, it's hard to know what happened in your case and if this error is intentional.
Can you please open a separate issue with more details?

> any reason as to not use an existing impl, eg npmjs.com/package/base-64 ?

Long term plan is to merge this lib into `graphql-js` which is a zero-dependency library so we can't depend on anything beyond core JS. It allows us to support a bunch of different environments, e.g. Deno.

**Comment by itajaja** [comment]
@IvanGoncharov thanks. maybe some of my test UUIDs are in that invalid category that now gets rejected. if I think they are valid, I'll open another task. Thanks!

**Pull request merged**
