### PR TITLE
Infer globalIdField type name if not specified

### PR DESCRIPTION
**Pull request by taion**
I got tired of always repeating the parent type's name. I'd imagine others would as well.

### CODE REVIEW

**Comment by taion** [comment]
BTW, might make sense to do this for `connectionDefinitions` as well; seems like `name` there is often just `nodeType.name`.

**Comment by taion** [comment]
Ping!

**Comment by dschafer** [comment]
Looks good to me, sorry for the delay!

**Comment by taion** [comment]
Thank you!

**Pull request merged**
